// <auto-generated />
using System;
using Estacionamento.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamento.Web.Migrations
{
    [DbContext(typeof(EstacionamentoDbContext))]
    [Migration("20260712170038_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Estacionamento.Domain.RegistroEstacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrosEstacionamento");
                });

            modelBuilder.Entity("Estacionamento.Domain.TabelaPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraAdicional")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraInicial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelasPreco");
                });
#pragma warning restore 612, 618
        }
    }
}
